# Generated by Django 4.0.5 on 2022-07-02 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corte', models.CharField(choices=[('Suprema', 'Suprema'), ('Apelaciones', 'Apelaciones'), ('Civil', 'Civil'), ('Familia', 'Familia'), ('Laboral', 'Laboral'), ('Cobranza', 'Cobranza'), ('Penal', 'Penal')], max_length=200)),
                ('tribunal', models.CharField(max_length=200)),
                ('nro_causa', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Causa',
                'verbose_name_plural': 'Causas',
                'db_table': 'causa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Litigante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('tipo_sujeto', models.CharField(max_length=200)),
                ('tipo_persona', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('ap_paterno', models.CharField(max_length=200)),
                ('ap_materno', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litigante',
                'verbose_name_plural': 'Litigantes',
                'db_table': 'litigante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[('Suprema', 'Suprema'), ('Apelaciones', 'Apelaciones'), ('Civil', 'Civil'), ('Familia', 'Familia'), ('Laboral', 'Laboral'), ('Cobranza', 'Cobranza'), ('Penal', 'Penal')])),
                ('asunto', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('litigante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.causa')),
                ('litigante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(null=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.causa')),
                ('litigante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.IntegerField(null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Generado'), (2, 'Pagado'), (3, 'Rechazado'), (4, 'Impago'), (5, 'Mora'), (6, 'Cobranza')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexapp.causa')),
                ('litigante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('litigante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='causa',
            name='litigante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lexapp.litigante'),
        ),
    ]
