# Generated by Django 4.0.5 on 2022-12-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresapp', '0002_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='dias_impartir',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
